name: Python program

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12, 3.9, 3.8]
  
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}

      - name: run python program
        run: python index.py
        
